class TaskException implements Exception {
  final String message;
  const TaskException(
    this.message,
  );
}
